# Generated by Django 5.2 on 2025-04-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_newsitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsItem",
        ),
    ]
