# Generated by Django 5.1.2 on 2025-02-05 02:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_comment_like_savedpost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="author",
        ),
    ]
