# Generated by Django 5.1.2 on 2025-04-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_savedpost_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinHistory',
        ),
    ]
