# Generated by Django 5.1.2 on 2025-04-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_delete_coinhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='coin_values',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
