# Generated by Django 5.1.2 on 2025-04-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_remove_communitypost_community_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
