# Generated by Django 5.1.2 on 2025-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('sentiment_score', models.FloatField(help_text='Normalized score between -1.0 (very negative) and +1.0 (very positive)')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], help_text='High-level label derived from sentiment_score', max_length=8)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sentiment_label'], name='tracker_new_sentime_db3b38_idx'), models.Index(fields=['-timestamp'], name='tracker_new_timesta_315483_idx')],
            },
        ),
    ]
