# Generated by Django 5.1.2 on 2025-04-05 22:18

import tracker.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_portfoliohistory_coin_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='binance_api_key',
            field=tracker.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='binance_secret_key',
            field=tracker.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='bybit_api_key',
            field=tracker.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='bybit_secret_key',
            field=tracker.models.EncryptedTextField(blank=True, default=''),
        ),
    ]
