# Generated by Django 5.1.2 on 2025-04-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_apikey_binance_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='active_exchanges',
            field=models.JSONField(default=list, help_text='List of active exchanges when this record was created'),
        ),
    ]
