# Generated by Django 5.1.2 on 2025-04-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
