# Generated by Django 5.1.2 on 2025-04-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_bookmark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tracker.blog'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'blog')},
        ),
    ]
