# Generated by Django 5.1.2 on 2025-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_bookmark_options_alter_bookmark_blog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='portfoliohistory',
            name='tracker_por_user_id_305258_idx',
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='snapshot_type',
            field=models.CharField(default='30min', help_text="Snapshot type: '30min' for near real-time updates or 'daily' for daily updates.", max_length=10),
        ),
    ]
