# Generated by Django 5.1.2 on 2025-04-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_community_communitypost_communitymembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitypost',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymembership',
            name='community',
        ),
        migrations.AlterUniqueTogether(
            name='communitymembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='communitymembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='author',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tracker.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'blog')},
            },
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='CommunityMembership',
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
